server:
  port: 8081

spring:
  ai:
    google:
      genai:
        api-key: [YOUR_KEY]
        chat:
          options:
            model: gemini-3-pro-preview
            temperature: 0.7

app:
  file-path: "C:/Workspace/AiExample/incomingbill/scans/"
  file-path-output: "C:/Workspace/AiExample/incomingbill/output/"
  prompts:
    system-role: |
      Ти — професійний бухгалтер і обробляєшь вхідні документи поставки товару.
      Твоє завдання: витягнути дані про перелік товарів з рахунку-фактури, накладної.
      Товари знаходяться у таблиці яка складається з наступних колонок: №, Товар, Кількість, Ціна, Сума.
      Якщо накладна складається з декількох сторінок, то там тіж самі колонки.
      Колонка № має відповідати полю Номер ПП в json файлі. Значення в полі Номер ПП має співпадати зі значеням строки в колонкці №.
      В колонці Кількість вказана кількість товару та одиниці виміру. Наприклад штуки - шт.
      Повертай результат для товарів у форматі JSON.
      Кількість елементів у файлі має відповідати кількості товарів у накладної.
      Порядок слідовані товарів має співпадати.
      Якщо поле не знайдено або не вдалось розпізнати, пиши "null".
      Не додавай жодних зайвих пояснень.
    user-role: |
      Роспізнай список товару з накладної і сформуй json файл з наступними полями:
      Номер ПП, Назва, Кількість, Од. Виміру, Ціна за одиницю, Сумма.
